stages:
  - prepare
  - build

install_dependence:
  stage: prepare
  script:
    - npm install --legacy-peer-deps
  cache:
    paths:
      - ./node_modules
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
  only:
    refs:
      - develop
    changes:
      - package.json
      - package-lock.json
  tags:
    - DEV

build-develop:
  stage: build
  script:
    - cp .env.example .env
    - sed -i "s~CI_API_URL~$CI_DEV_API_URL~g" .env
    - sed -i "s~CI_CD_USER_URL~$CI_DEV_USER_URL~g" .env
    - cat .env
    - npm run build
    - sudo rsync -hrvzgo --chown=centos:centos --exclude=.git --delete $CI_PROJECT_DIR/ /srv/admin/
    - aws s3 sync --cache-control 'max-age=604800' --exclude index.html build/ s3://nsk-dev-web/admin/ --delete
    - aws s3 sync --cache-control 'no-cache' build/ s3://nsk-dev-web/admin/
    - aws cloudfront create-invalidation --distribution-id $CI_DEV_CLOUDFONT_ID --paths '/*'
  cache:
    paths:
      - ./node_modules
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  only:
    - develop
  tags:
    - DEV

#################
install_dependence_staging:
  stage: prepare
  script:
    - npm install --legacy-peer-deps
  cache:
    paths:
      - ./node_modules
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
  only:
    refs:
      - staging
    changes:
      - package.json
      - package-lock.json
  tags:
    - STG


build-staging:
  stage: build
  script:
    - cp .env.example .env
    - sed -i "s~CI_API_URL~$CI_STG_API_URL~g" .env
    - sed -i "s~CI_CD_USER_URL~$CI_STG_USER_URL~g" .env
    - npm run build
    - sudo rsync -hrvzgo --chown=centos:centos --exclude=.git --delete $CI_PROJECT_DIR/ /srv/admin/
    - aws s3 sync --cache-control 'max-age=604800' --exclude index.html build/ $CI_STG_S3_WEB/admin/ --delete
    - aws s3 sync --cache-control 'no-cache' build/ $CI_STG_S3_WEB/admin/
    - aws cloudfront create-invalidation --distribution-id $CI_STG_CLOUDFONT_ID --paths '/*'
  cache:
    paths:
      - ./node_modules
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
  only:
    - staging
  tags:
    - STG
